### ISSUE TITLE
Application crashes if we search then follow/save an event

### ISSUE THREAD

**Issue by AlouchLaBouche** [SwEnt-Group13/Unio#266]
Another issue is encountered with the application. When first searching for an event or a association, or more generally, when we use the searchViewModel, and then we try to follow/save an event, an unexpected crash happens. 
This is the error message the we get in the log cat :
```FATAL EXCEPTION: main
    Process: com.android.unio, PID: 26561
    java.lang.IllegalStateException: Already resumed
    	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
	at com.android.unio.model.search.SearchRepository$eventDocumentToEvent$2$1.invoke(SearchRepository.kt:216)
	at com.android.unio.model.search.SearchRepository$eventDocumentToEvent$2$1.invoke(SearchRepository.kt:214)
	at com.android.unio.model.event.EventRepositoryFirestore.getEventWithId$lambda$1(EventRepositoryFirestore.kt:65)
    	at com.android.unio.model.event.EventRepositoryFirestore.$r8$lambda$mHghD2Dd1GuRYS7HdibPomGrHjs(Unknown Source:0)
	at com.android.unio.model.event.EventRepositoryFirestore$$ExternalSyntheticLambda2.onEvent(D8$$SyntheticClass:0)
    	at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$6$com-google-firebase-firestore-DocumentReference(DocumentReference.java:525)
    	at com.google.firebase.firestore.DocumentReference$$ExternalSyntheticLambda5.onEvent(D8$$SyntheticClass:0)
    	at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0$com-google-firebase-firestore-core-AsyncEventListener(AsyncEventListener.java:42)
    	at com.google.firebase.firestore.core.AsyncEventListener$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
    	at android.os.Handler.handleCallback(Handler.java:958)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loopOnce(Looper.java:257)
    	at android.os.Looper.loop(Looper.java:368)
    	at android.app.ActivityThread.main(ActivityThread.java:8826)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```
    	
It seems that every time we use the search view model, (even inputting a single character) all other Firebase will fail.

**Comment by Romainhir** [comment]
The bug cames indeed from the search repository. For some reason, in "associationDocumentToAssociation", the couroutine was resumed once more (even if it was already resumed during a search). The fix is easy once the bug is now identified. We can just check if the coroutine is not already resumed (with continuation.context.isActive)
